
#include <QVariant>
#include <QMap>

// this file is machine generated, DO NOT EDIT
// last generated at 2014-08-30 06:28:54 UTC

const QMap<QString, QVariantMap> libretro_cores_info {
    { "2048_libretro", {
        { "display_name", "2048" },
        { "authors", "Gabriele Cirulli" },
        { "supported_extensions", "" },
        { "corename", "2048" },
        { "systemname", "2048 game clone" },
        { "license", "GPLv3" },
        { "permissions", "" },
        { "display_version", "1.0" },
        { "need_fullpath", false },
        { "block_extract", false },
        { "supports_no_game", true }
    } },
    { "3dengine_libretro", {
        { "authors", "Team Libretro" },
        { "display_name", "3D Engine" },
        { "supported_extensions", "png|jpg|mtl|obj" },
        { "corename", "3DEngine" },
        { "manufacturer", "Various" },
        { "systemname", "3D Engine" },
        { "license", "" },
        { "permissions", "" },
        { "display_version", "v1" },
        { "need_fullpath", false },
        { "block_extract", false },
        { "supports_no_game", false }
    } },
    { "4do_libretro", {
        { "display_name", "3DO (4DO)" },
        { "authors", "JohnnyDude|FreeDO team" },
        { "supported_extensions", "iso|cue" },
        { "corename", "4DO" },
        { "manufacturer", "Various" },
        { "systemname", "3DO" },
        { "license", "LGPL with additional notes" },
        { "permissions", "" },
        { "display_version", "v1.3.2.3" },
        { "need_fullpath", true },
        { "block_extract", false },
        { "supports_no_game", false },
        { "firmware_count", "1" },
        { "firmware0_desc", "panafz10.bin (Panasonic FZ-10 BIOS)" },
        { "firmware0_path", "panafz10.bin" },
        { "firmware0_opt", false }
    } },
    { "bluemsx_libretro", {
        { "display_name", "MSX/SVI/ColecoVision/SG-1000 (blueMSX)" },
        { "authors", "Daniel Vik" },
        { "supported_extensions", "rom|ri|mx1|mx2|col|sg|sc" },
        { "corename", "blueMSX" },
        { "manufacturer", "Various" },
        { "systemname", "MSX/SVI/ColecoVision/SG-1000" },
        { "license", "GPLv2" },
        { "permissions", "" },
        { "display_version", "svn" },
        { "need_fullpath", true },
        { "block_extract", false },
        { "supports_no_game", false }
    } },
    { "bnes_libretro", {
        { "display_name", "NES / Famicom (bNES)" },
        { "authors", "byuu" },
        { "supported_extensions", "nes" },
        { "corename", "bNES/higan" },
        { "manufacturer", "Nintendo" },
        { "systemname", "Nintendo Entertainment System" },
        { "license", "GPLv3" },
        { "permissions", "" },
        { "display_version", "v083" },
        { "need_fullpath", false },
        { "block_extract", false },
        { "supports_no_game", false }
    } },
    { "bsnes_accuracy_libretro", {
        { "display_name", "SNES / Super Famicom (bSNES Accuracy)" },
        { "authors", "byuu" },
        { "supported_extensions", "sfc|smc|bml" },
        { "corename", "bsnes/higan Accuracy" },
        { "manufacturer", "Nintendo" },
        { "systemname", "Super Nintendo Entertainment System" },
        { "license", "GPLv3" },
        { "permissions", "" },
        { "display_version", "v094 (Accuracy)" },
        { "need_fullpath", false },
        { "block_extract", false },
        { "supports_no_game", false },
        { "firmware_count", "18" },
        { "firmware0_desc", "dsp1.data.rom (DSP1 DATA)" },
        { "firmware0_path", "dsp1.data.rom" },
        { "firmware0_opt", true },
        { "firmware1_desc", "dsp1.program.rom (DSP1 PROGRAM)" },
        { "firmware1_path", "dsp1.program.rom" },
        { "firmware1_opt", true },
        { "firmware2_desc", "dsp1b.data.rom (DSP1B DATA)" },
        { "firmware2_path", "dsp1b.data.rom" },
        { "firmware2_opt", true },
        { "firmware3_desc", "dsp1b.program.rom (DSP1B PROGRAM)" },
        { "firmware3_path", "dsp1b.program.rom" },
        { "firmware3_opt", true },
        { "firmware4_desc", "dsp2.data.rom (DSP2 DATA)" },
        { "firmware4_path", "dsp2.data.rom" },
        { "firmware4_opt", true },
        { "firmware5_desc", "dsp2.program.rom (DSP2 PROGRAM)" },
        { "firmware5_path", "dsp2.program.rom" },
        { "firmware5_opt", true },
        { "firmware6_desc", "dsp3.data.rom (DSP3 DATA)" },
        { "firmware6_path", "dsp3.data.rom" },
        { "firmware6_opt", true },
        { "firmware7_desc", "dsp3.program.rom (DSP3 PROGRAM)" },
        { "firmware7_path", "dsp3.program.rom" },
        { "firmware7_opt", true },
        { "firmware8_desc", "dsp4.data.rom (DSP4 DATA)" },
        { "firmware8_path", "dsp4.data.rom" },
        { "firmware8_opt", true },
        { "firmware9_desc", "dsp4.program.rom (DSP4 PROGRAM)" },
        { "firmware9_path", "dsp4.program.rom" },
        { "firmware9_opt", true },
        { "firmware10_desc", "cx4.data.rom (Cx4 DATA)" },
        { "firmware10_path", "cx4.data.rom" },
        { "firmware10_opt", true },
        { "firmware11_desc", "st010.data.rom (ST-0010 DATA)" },
        { "firmware11_path", "st010.data.rom" },
        { "firmware11_opt", true },
        { "firmware12_desc", "st010.program.rom (ST-0010 PROGRAM)" },
        { "firmware12_path", "st010.program.rom" },
        { "firmware12_opt", true },
        { "firmware13_desc", "st011.program.rom (ST-0011 PROGRAM)" },
        { "firmware13_path", "st011.program.rom" },
        { "firmware13_opt", true },
        { "firmware14_desc", "st011.program.rom (ST-0011 PROGRAM)" },
        { "firmware14_path", "st011.program.rom" },
        { "firmware14_opt", true },
        { "firmware15_desc", "st018.program.rom (ST-0018 PROGRAM)" },
        { "firmware15_path", "st018.program.rom" },
        { "firmware15_opt", true },
        { "firmware16_desc", "st018.program.rom (ST-0018 PROGRAM)" },
        { "firmware16_path", "st018.program.rom" },
        { "firmware16_opt", true },
        { "firmware17_desc", "sgb.boot.rom (SGB BOOT)" },
        { "firmware17_path", "sgb.boot.rom" },
        { "firmware17_opt", true },
        { "notes", "- core uses split ROMS for special chip games|- notable DSP1/DSP1B games: Super Mario Kart / Pilotwings|- notable DSP2 games: Dungeon Master|- notable DSP3 games: SD Gundam GX|- notable DSP4 games: Top Gear 3000|- notable Cx4 games: Mega Man X2 / Mega Man X3|- sgb emulation only works from command line" }
    } },
    { "bsnes_balanced_libretro", {
        { "display_name", "SNES / Super Famicom (bSNES Balanced)" },
        { "authors", "byuu" },
        { "supported_extensions", "sfc|smc|bml" },
        { "corename", "bsnes/higan Balanced" },
        { "manufacturer", "Nintendo" },
        { "systemname", "Super Nintendo Entertainment System" },
        { "license", "GPLv3" },
        { "permissions", "" },
        { "display_version", "v094 (Balanced)" },
        { "need_fullpath", false },
        { "block_extract", false },
        { "supports_no_game", false },
        { "firmware_count", "18" },
        { "firmware0_desc", "dsp1.data.rom (DSP1 DATA)" },
        { "firmware0_path", "dsp1.data.rom" },
        { "firmware0_opt", true },
        { "firmware1_desc", "dsp1.program.rom (DSP1 PROGRAM)" },
        { "firmware1_path", "dsp1.program.rom" },
        { "firmware1_opt", true },
        { "firmware2_desc", "dsp1b.data.rom (DSP1B DATA)" },
        { "firmware2_path", "dsp1b.data.rom" },
        { "firmware2_opt", true },
        { "firmware3_desc", "dsp1b.program.rom (DSP1B PROGRAM)" },
        { "firmware3_path", "dsp1b.program.rom" },
        { "firmware3_opt", true },
        { "firmware4_desc", "dsp2.data.rom (DSP2 DATA)" },
        { "firmware4_path", "dsp2.data.rom" },
        { "firmware4_opt", true },
        { "firmware5_desc", "dsp2.program.rom (DSP2 PROGRAM)" },
        { "firmware5_path", "dsp2.program.rom" },
        { "firmware5_opt", true },
        { "firmware6_desc", "dsp3.data.rom (DSP3 DATA)" },
        { "firmware6_path", "dsp3.data.rom" },
        { "firmware6_opt", true },
        { "firmware7_desc", "dsp3.program.rom (DSP3 PROGRAM)" },
        { "firmware7_path", "dsp3.program.rom" },
        { "firmware7_opt", true },
        { "firmware8_desc", "dsp4.data.rom (DSP4 DATA)" },
        { "firmware8_path", "dsp4.data.rom" },
        { "firmware8_opt", true },
        { "firmware9_desc", "dsp4.program.rom (DSP4 PROGRAM)" },
        { "firmware9_path", "dsp4.program.rom" },
        { "firmware9_opt", true },
        { "firmware10_desc", "cx4.data.rom (Cx4 DATA)" },
        { "firmware10_path", "cx4.data.rom" },
        { "firmware10_opt", true },
        { "firmware11_desc", "st010.data.rom (ST-0010 DATA)" },
        { "firmware11_path", "st010.data.rom" },
        { "firmware11_opt", true },
        { "firmware12_desc", "st010.program.rom (ST-0010 PROGRAM)" },
        { "firmware12_path", "st010.program.rom" },
        { "firmware12_opt", true },
        { "firmware13_desc", "st011.program.rom (ST-0011 PROGRAM)" },
        { "firmware13_path", "st011.program.rom" },
        { "firmware13_opt", true },
        { "firmware14_desc", "st011.program.rom (ST-0011 PROGRAM)" },
        { "firmware14_path", "st011.program.rom" },
        { "firmware14_opt", true },
        { "firmware15_desc", "st018.program.rom (ST-0018 PROGRAM)" },
        { "firmware15_path", "st018.program.rom" },
        { "firmware15_opt", true },
        { "firmware16_desc", "st018.program.rom (ST-0018 PROGRAM)" },
        { "firmware16_path", "st018.program.rom" },
        { "firmware16_opt", true },
        { "firmware17_desc", "sgb.boot.rom (SGB BOOT)" },
        { "firmware17_path", "sgb.boot.rom" },
        { "firmware17_opt", true },
        { "notes", "- core uses split ROMS for special chip games|- notable DSP1/DSP1B games: Super Mario Kart / Pilotwings|- notable DSP2 games: Dungeon Master|- notable DSP3 games: SD Gundam GX|- notable DSP4 games: Top Gear 3000|- notable Cx4 games: Mega Man X2 / Mega Man X3|- sgb emulation only works from command line" }
    } },
    { "bsnes_cplusplus98_libretro", {
        { "display_name", "SNES / Super Famicom (bSNES C++98 (v085))" },
        { "authors", "byuu|Themaister|Ver GreenEyes" },
        { "supported_extensions", "sfc|smc" },
        { "corename", "bsnes C++98 (v085)" },
        { "manufacturer", "Nintendo" },
        { "systemname", "Super Nintendo Entertainment System" },
        { "license", "GPLv3" },
        { "permissions", "" },
        { "display_version", "v085 (Performance)" },
        { "need_fullpath", false },
        { "block_extract", false },
        { "supports_no_game", false }
    } },
    { "bsnes_mercury_accuracy_libretro", {
        { "display_name", "SNES / Super Famicom (bSNES Mercury Accuracy)" },
        { "authors", "byuu" },
        { "supported_extensions", "sfc|smc|bml" },
        { "corename", "bsnes/higan Mercury Accuracy" },
        { "manufacturer", "Nintendo" },
        { "systemname", "Super Nintendo Entertainment System" },
        { "license", "GPLv3" },
        { "permissions", "" },
        { "display_version", "v094 (Mercury Accuracy)" },
        { "need_fullpath", false },
        { "block_extract", false },
        { "supports_no_game", false },
        { "firmware_count", "18" },
        { "firmware0_desc", "dsp1.data.rom (DSP1 DATA)" },
        { "firmware0_path", "dsp1.data.rom" },
        { "firmware0_opt", true },
        { "firmware1_desc", "dsp1.program.rom (DSP1 PROGRAM)" },
        { "firmware1_path", "dsp1.program.rom" },
        { "firmware1_opt", true },
        { "firmware2_desc", "dsp1b.data.rom (DSP1B DATA)" },
        { "firmware2_path", "dsp1b.data.rom" },
        { "firmware2_opt", true },
        { "firmware3_desc", "dsp1b.program.rom (DSP1B PROGRAM)" },
        { "firmware3_path", "dsp1b.program.rom" },
        { "firmware3_opt", true },
        { "firmware4_desc", "dsp2.data.rom (DSP2 DATA)" },
        { "firmware4_path", "dsp2.data.rom" },
        { "firmware4_opt", true },
        { "firmware5_desc", "dsp2.program.rom (DSP2 PROGRAM)" },
        { "firmware5_path", "dsp2.program.rom" },
        { "firmware5_opt", true },
        { "firmware6_desc", "dsp3.data.rom (DSP3 DATA)" },
        { "firmware6_path", "dsp3.data.rom" },
        { "firmware6_opt", true },
        { "firmware7_desc", "dsp3.program.rom (DSP3 PROGRAM)" },
        { "firmware7_path", "dsp3.program.rom" },
        { "firmware7_opt", true },
        { "firmware8_desc", "dsp4.data.rom (DSP4 DATA)" },
        { "firmware8_path", "dsp4.data.rom" },
        { "firmware8_opt", true },
        { "firmware9_desc", "dsp4.program.rom (DSP4 PROGRAM)" },
        { "firmware9_path", "dsp4.program.rom" },
        { "firmware9_opt", true },
        { "firmware10_desc", "cx4.data.rom (Cx4 DATA)" },
        { "firmware10_path", "cx4.data.rom" },
        { "firmware10_opt", true },
        { "firmware11_desc", "st010.data.rom (ST-0010 DATA)" },
        { "firmware11_path", "st010.data.rom" },
        { "firmware11_opt", true },
        { "firmware12_desc", "st010.program.rom (ST-0010 PROGRAM)" },
        { "firmware12_path", "st010.program.rom" },
        { "firmware12_opt", true },
        { "firmware13_desc", "st011.program.rom (ST-0011 PROGRAM)" },
        { "firmware13_path", "st011.program.rom" },
        { "firmware13_opt", true },
        { "firmware14_desc", "st011.program.rom (ST-0011 PROGRAM)" },
        { "firmware14_path", "st011.program.rom" },
        { "firmware14_opt", true },
        { "firmware15_desc", "st018.program.rom (ST-0018 PROGRAM)" },
        { "firmware15_path", "st018.program.rom" },
        { "firmware15_opt", true },
        { "firmware16_desc", "st018.program.rom (ST-0018 PROGRAM)" },
        { "firmware16_path", "st018.program.rom" },
        { "firmware16_opt", true },
        { "firmware17_desc", "sgb.boot.rom (SGB BOOT)" },
        { "firmware17_path", "sgb.boot.rom" },
        { "firmware17_opt", true },
        { "notes", "- core uses split ROMS for special chip games|- notable DSP1/DSP1B games: Super Mario Kart / Pilotwings|- notable DSP2 games: Dungeon Master|- notable DSP3 games: SD Gundam GX|- notable DSP4 games: Top Gear 3000|- notable Cx4 games: Mega Man X2 / Mega Man X3|- sgb emulation only works from command line" }
    } },
    { "bsnes_mercury_balanced_libretro", {
        { "display_name", "SNES / Super Famicom (bSNES Mercury Balanced)" },
        { "authors", "byuu" },
        { "supported_extensions", "sfc|smc|bml" },
        { "corename", "bsnes/higan Mercury Balanced" },
        { "manufacturer", "Nintendo" },
        { "systemname", "Super Nintendo Entertainment System" },
        { "license", "GPLv3" },
        { "permissions", "" },
        { "display_version", "v094 (Mercury Balanced)" },
        { "need_fullpath", false },
        { "block_extract", false },
        { "supports_no_game", false },
        { "firmware_count", "18" },
        { "firmware0_desc", "dsp1.data.rom (DSP1 DATA)" },
        { "firmware0_path", "dsp1.data.rom" },
        { "firmware0_opt", true },
        { "firmware1_desc", "dsp1.program.rom (DSP1 PROGRAM)" },
        { "firmware1_path", "dsp1.program.rom" },
        { "firmware1_opt", true },
        { "firmware2_desc", "dsp1b.data.rom (DSP1B DATA)" },
        { "firmware2_path", "dsp1b.data.rom" },
        { "firmware2_opt", true },
        { "firmware3_desc", "dsp1b.program.rom (DSP1B PROGRAM)" },
        { "firmware3_path", "dsp1b.program.rom" },
        { "firmware3_opt", true },
        { "firmware4_desc", "dsp2.data.rom (DSP2 DATA)" },
        { "firmware4_path", "dsp2.data.rom" },
        { "firmware4_opt", true },
        { "firmware5_desc", "dsp2.program.rom (DSP2 PROGRAM)" },
        { "firmware5_path", "dsp2.program.rom" },
        { "firmware5_opt", true },
        { "firmware6_desc", "dsp3.data.rom (DSP3 DATA)" },
        { "firmware6_path", "dsp3.data.rom" },
        { "firmware6_opt", true },
        { "firmware7_desc", "dsp3.program.rom (DSP3 PROGRAM)" },
        { "firmware7_path", "dsp3.program.rom" },
        { "firmware7_opt", true },
        { "firmware8_desc", "dsp4.data.rom (DSP4 DATA)" },
        { "firmware8_path", "dsp4.data.rom" },
        { "firmware8_opt", true },
        { "firmware9_desc", "dsp4.program.rom (DSP4 PROGRAM)" },
        { "firmware9_path", "dsp4.program.rom" },
        { "firmware9_opt", true },
        { "firmware10_desc", "cx4.data.rom (Cx4 DATA)" },
        { "firmware10_path", "cx4.data.rom" },
        { "firmware10_opt", true },
        { "firmware11_desc", "st010.data.rom (ST-0010 DATA)" },
        { "firmware11_path", "st010.data.rom" },
        { "firmware11_opt", true },
        { "firmware12_desc", "st010.program.rom (ST-0010 PROGRAM)" },
        { "firmware12_path", "st010.program.rom" },
        { "firmware12_opt", true },
        { "firmware13_desc", "st011.program.rom (ST-0011 PROGRAM)" },
        { "firmware13_path", "st011.program.rom" },
        { "firmware13_opt", true },
        { "firmware14_desc", "st011.program.rom (ST-0011 PROGRAM)" },
        { "firmware14_path", "st011.program.rom" },
        { "firmware14_opt", true },
        { "firmware15_desc", "st018.program.rom (ST-0018 PROGRAM)" },
        { "firmware15_path", "st018.program.rom" },
        { "firmware15_opt", true },
        { "firmware16_desc", "st018.program.rom (ST-0018 PROGRAM)" },
        { "firmware16_path", "st018.program.rom" },
        { "firmware16_opt", true },
        { "firmware17_desc", "sgb.boot.rom (SGB BOOT)" },
        { "firmware17_path", "sgb.boot.rom" },
        { "firmware17_opt", true },
        { "notes", "- core uses split ROMS for special chip games|- notable DSP1/DSP1B games: Super Mario Kart / Pilotwings|- notable DSP2 games: Dungeon Master|- notable DSP3 games: SD Gundam GX|- notable DSP4 games: Top Gear 3000|- notable Cx4 games: Mega Man X2 / Mega Man X3|- sgb emulation only works from command line" }
    } },
    { "bsnes_mercury_performance_libretro", {
        { "display_name", "SNES / Super Famicom (bSNES Mercury Performance)" },
        { "authors", "byuu" },
        { "supported_extensions", "sfc|smc|bml" },
        { "corename", "bsnes/higan Mercury Performance" },
        { "manufacturer", "Nintendo" },
        { "systemname", "Super Nintendo Entertainment System" },
        { "license", "GPLv3" },
        { "permissions", "" },
        { "display:version", "v094 (Mercury Performance)" },
        { "need_fullpath", false },
        { "block_extract", false },
        { "supports_no_game", false },
        { "firmware_count", "17" },
        { "firmware0_desc", "dsp1.data.rom (DSP1 DATA)" },
        { "firmware0_path", "dsp1.data.rom" },
        { "firmware0_opt", true },
        { "firmware1_desc", "dsp1.program.rom (DSP1 PROGRAM)" },
        { "firmware1_path", "dsp1.program.rom" },
        { "firmware1_opt", true },
        { "firmware2_desc", "dsp1b.data.rom (DSP1B DATA)" },
        { "firmware2_path", "dsp1b.data.rom" },
        { "firmware2_opt", true },
        { "firmware3_desc", "dsp1b.program.rom (DSP1B PROGRAM)" },
        { "firmware3_path", "dsp1b.program.rom" },
        { "firmware3_opt", true },
        { "firmware4_desc", "dsp2.data.rom (DSP2 DATA)" },
        { "firmware4_path", "dsp2.data.rom" },
        { "firmware4_opt", true },
        { "firmware5_desc", "dsp2.program.rom (DSP2 PROGRAM)" },
        { "firmware5_path", "dsp2.program.rom" },
        { "firmware5_opt", true },
        { "firmware6_desc", "dsp3.data.rom (DSP3 DATA)" },
        { "firmware6_path", "dsp3.data.rom" },
        { "firmware6_opt", true },
        { "firmware7_desc", "dsp3.program.rom (DSP3 PROGRAM)" },
        { "firmware7_path", "dsp3.program.rom" },
        { "firmware7_opt", true },
        { "firmware8_desc", "dsp4.data.rom (DSP4 DATA)" },
        { "firmware8_path", "dsp4.data.rom" },
        { "firmware8_opt", true },
        { "firmware9_desc", "dsp4.program.rom (DSP4 PROGRAM)" },
        { "firmware9_path", "dsp4.program.rom" },
        { "firmware9_opt", true },
        { "firmware10_desc", "st010.data.rom (ST-0010 DATA)" },
        { "firmware10_path", "st010.data.rom" },
        { "firmware10_opt", true },
        { "firmware11_desc", "st010.program.rom (ST-0010 PROGRAM)" },
        { "firmware11_path", "st010.program.rom" },
        { "firmware11_opt", true },
        { "firmware12_desc", "st011.program.rom (ST-0011 PROGRAM)" },
        { "firmware12_path", "st011.program.rom" },
        { "firmware12_opt", true },
        { "firmware13_desc", "st011.program.rom (ST-0011 PROGRAM)" },
        { "firmware13_path", "st011.program.rom" },
        { "firmware13_opt", true },
        { "firmware14_desc", "st018.program.rom (ST-0018 PROGRAM)" },
        { "firmware14_path", "st018.program.rom" },
        { "firmware14_opt", true },
        { "firmware15_desc", "st018.program.rom (ST-0018 PROGRAM)" },
        { "firmware15_path", "st018.program.rom" },
        { "firmware15_opt", true },
        { "firmware16_desc", "sgb.boot.rom (SGB BOOT)" },
        { "firmware16_path", "sgb.boot.rom" },
        { "firmware16_opt", true },
        { "notes", "- core uses split ROMS for special chip games|- notable DSP1/DSP1B games: Super Mario Kart / Pilotwings|- Cx4 emulation broken|- notable DSP2 games: Dungeon Master|- notable DSP3 games: SD Gundam GX|- notable DSP4 games: Top Gear 3000" }
    } },
    { "bsnes_performance_libretro", {
        { "display_name", "SNES / Super Famicom (bSNES Performance)" },
        { "authors", "byuu" },
        { "supported_extensions", "sfc|smc|bml" },
        { "corename", "bsnes/higan Performance" },
        { "manufacturer", "Nintendo" },
        { "systemname", "Super Nintendo Entertainment System" },
        { "license", "GPLv3" },
        { "permissions", "" },
        { "display:version", "v094 (Performance)" },
        { "need_fullpath", false },
        { "block_extract", false },
        { "supports_no_game", false },
        { "firmware_count", "17" },
        { "firmware0_desc", "dsp1.data.rom (DSP1 DATA)" },
        { "firmware0_path", "dsp1.data.rom" },
        { "firmware0_opt", true },
        { "firmware1_desc", "dsp1.program.rom (DSP1 PROGRAM)" },
        { "firmware1_path", "dsp1.program.rom" },
        { "firmware1_opt", true },
        { "firmware2_desc", "dsp1b.data.rom (DSP1B DATA)" },
        { "firmware2_path", "dsp1b.data.rom" },
        { "firmware2_opt", true },
        { "firmware3_desc", "dsp1b.program.rom (DSP1B PROGRAM)" },
        { "firmware3_path", "dsp1b.program.rom" },
        { "firmware3_opt", true },
        { "firmware4_desc", "dsp2.data.rom (DSP2 DATA)" },
        { "firmware4_path", "dsp2.data.rom" },
        { "firmware4_opt", true },
        { "firmware5_desc", "dsp2.program.rom (DSP2 PROGRAM)" },
        { "firmware5_path", "dsp2.program.rom" },
        { "firmware5_opt", true },
        { "firmware6_desc", "dsp3.data.rom (DSP3 DATA)" },
        { "firmware6_path", "dsp3.data.rom" },
        { "firmware6_opt", true },
        { "firmware7_desc", "dsp3.program.rom (DSP3 PROGRAM)" },
        { "firmware7_path", "dsp3.program.rom" },
        { "firmware7_opt", true },
        { "firmware8_desc", "dsp4.data.rom (DSP4 DATA)" },
        { "firmware8_path", "dsp4.data.rom" },
        { "firmware8_opt", true },
        { "firmware9_desc", "dsp4.program.rom (DSP4 PROGRAM)" },
        { "firmware9_path", "dsp4.program.rom" },
        { "firmware9_opt", true },
        { "firmware10_desc", "st010.data.rom (ST-0010 DATA)" },
        { "firmware10_path", "st010.data.rom" },
        { "firmware10_opt", true },
        { "firmware11_desc", "st010.program.rom (ST-0010 PROGRAM)" },
        { "firmware11_path", "st010.program.rom" },
        { "firmware11_opt", true },
        { "firmware12_desc", "st011.program.rom (ST-0011 PROGRAM)" },
        { "firmware12_path", "st011.program.rom" },
        { "firmware12_opt", true },
        { "firmware13_desc", "st011.program.rom (ST-0011 PROGRAM)" },
        { "firmware13_path", "st011.program.rom" },
        { "firmware13_opt", true },
        { "firmware14_desc", "st018.program.rom (ST-0018 PROGRAM)" },
        { "firmware14_path", "st018.program.rom" },
        { "firmware14_opt", true },
        { "firmware15_desc", "st018.program.rom (ST-0018 PROGRAM)" },
        { "firmware15_path", "st018.program.rom" },
        { "firmware15_opt", true },
        { "firmware16_desc", "sgb.boot.rom (SGB BOOT)" },
        { "firmware16_path", "sgb.boot.rom" },
        { "firmware16_opt", true },
        { "notes", "- core uses split ROMS for special chip games|- notable DSP1/DSP1B games: Super Mario Kart / Pilotwings|- Cx4 emulation broken|- notable DSP2 games: Dungeon Master|- notable DSP3 games: SD Gundam GX|- notable DSP4 games: Top Gear 3000" }
    } },
    { "desmume_libretro", {
        { "display_name", "Nintendo DS (DeSmuME)" },
        { "authors", "YopYop156|Zeromus" },
        { "supported_extensions", "nds|bin" },
        { "corename", "DeSmuME" },
        { "manufacturer", "Nintendo" },
        { "systemname", "Nintendo DS" },
        { "license", "GPLv2" },
        { "permissions", "" },
        { "display_version", "svn" },
        { "need_fullpath", true },
        { "block_extract", false },
        { "supports_no_game", false }
    } },
    { "dinothawr_libretro", {
        { "display_name", "Dinothawr" },
        { "authors", "Themaister|Agnes Heyer" },
        { "supported_extensions", "game" },
        { "corename", "Dinothawr" },
        { "systemname", "Game" },
        { "license", "Non-commercial" },
        { "permissions", "" },
        { "display_version", "v1.0" },
        { "need_fullpath", true },
        { "block_extract", false },
        { "supports_no_game", false }
    } },
    { "dosbox_libretro", {
        { "display_name", "DOS (DOSBox)" },
        { "supported_extensions", "exe|com|bat|conf" },
        { "corename", "DOSBox" },
        { "systemname", "DOS" },
        { "license", "GPLv2" },
        { "permissions", "" },
        { "display_version", "svn" },
        { "need_fullpath", true },
        { "block_extract", false },
        { "supports_no_game", true }
    } },
    { "example", {

    } },
    { "fb_alpha_libretro", {
        { "display_name", "Arcade (FBA)" },
        { "authors", "Barry Harris" },
        { "supported_extensions", "iso|zip" },
        { "corename", "Final Burn Alpha" },
        { "manufacturer", "Various" },
        { "systemname", "Arcade (various)" },
        { "license", "Non-commercial" },
        { "permissions", "" },
        { "display_version", "v0.2.97.30" },
        { "need_fullpath", true },
        { "block_extract", true },
        { "supports_no_game", false },
        { "notes", "- BIOS files go into the ROM directory|" }
    } },
    { "fba_cores_cps1_libretro", {
        { "display_name", "CPS1 (FBA)" },
        { "authors", "Team FB Alpha" },
        { "supported_extensions", "zip" },
        { "corename", "Final Burn Alpha - CPS1" },
        { "manufacturer", "Various" },
        { "systemname", "CP System" },
        { "license", "Non-commercial" },
        { "permissions", "" },
        { "notes", "- BIOS files go into the ROM directory|" }
    } },
    { "fba_cores_cps2_libretro", {
        { "display_name", "CPS2 (FBA)" },
        { "authors", "Team FB Alpha" },
        { "supported_extensions", "zip" },
        { "corename", "Final Burn Alpha - CPS2" },
        { "manufacturer", "Various" },
        { "systemname", "CP System II" },
        { "license", "Non-commercial" },
        { "permissions", "" },
        { "notes", "- BIOS files go into the ROM directory|" }
    } },
    { "fba_cores_neo_libretro", {
        { "display_name", "Neo Geo (FBA)" },
        { "authors", "Team FB Alpha" },
        { "supported_extensions", "zip" },
        { "corename", "Final Burn Alpha - Neo Geo" },
        { "manufacturer", "Various" },
        { "systemname", "Neo Geo" },
        { "license", "Non-commercial" },
        { "permissions", "" },
        { "notes", "- BIOS files go into the ROM directory|" }
    } },
    { "fceumm_libretro", {
        { "display_name", "NES / Famicom (FCEUmm)" },
        { "supported_extensions", "fds|nes|unif" },
        { "authors", "CaH4e3|FCEU Team" },
        { "corename", "FCEUmm" },
        { "manufacturer", "Nintendo" },
        { "systemname", "Nintendo Entertainment System" },
        { "license", "GPLv2" },
        { "permissions", "" },
        { "firmware_count", "1" },
        { "firmware0_desc", "disksys.rom (Famicom Disk System BIOS)" },
        { "firmware0_path", "disksys.rom" },
        { "firmware0_opt", false },
        { "display_version", "(SVN)" },
        { "need_fullpath", true },
        { "block_extract", false },
        { "supports_no_game", false }
    } },
    { "ffmpeg_libretro", {
        { "display_name", "FFmpeg" },
        { "supported_extensions", "mkv|avi|f4v|f4f|3gp|ogm|flv|mp4|mp3|flac|ogg|m4a" },
        { "corename", "FFmpeg" },
        { "systemname", "FFmpeg" },
        { "license", "LGPLv2, GPLv2" },
        { "permissions", "" },
        { "display:version", "v1" },
        { "need_fullpath", true },
        { "block_extract", false },
        { "supports_no_game", false }
    } },
    { "fmsx_libretro", {
        { "display_name", "MSX (fMSX)" },
        { "authors", "Marat Fayzullin" },
        { "supported_extensions", "rom|mx1|mx2" },
        { "corename", "fMSX" },
        { "manufacturer", "Various" },
        { "systemname", "MSX" },
        { "license", "Non-commercial" },
        { "permissions", "" },
        { "display_version", "3.9" },
        { "need_fullpath", true },
        { "block_extract", false },
        { "supports_no_game", false },
        { "firmware_count", "5" },
        { "firmware0_desc", "MSX.ROM (MSX BIOS)" },
        { "firmware0_path", "MSX.ROM" },
        { "firmware0_opt", false },
        { "firmware1_desc", "MSX2.ROM (MSX2 BIOS)" },
        { "firmware1_path", "MSX2.ROM" },
        { "firmware1_opt", false },
        { "firmware2_desc", "MSX2EXT.ROM (MSX2 ExtROM)" },
        { "firmware2_path", "MSX2EXT.ROM" },
        { "firmware2_opt", false },
        { "firmware3_desc", "MSX2P.ROM (MSX2+ BIOS)" },
        { "firmware3_path", "MSX2P.ROM" },
        { "firmware3_opt", false },
        { "firmware4_desc", "MSX2PEXT.ROM (MSX2+ ExtROM)" },
        { "firmware4_path", "MSX2PEXT.ROM" },
        { "firmware4_opt", false }
    } },
    { "gambatte_libretro", {
        { "display_name", "Game Boy / Game Boy Color (Gambatte)" },
        { "authors", "Sinamas" },
        { "supported_extensions", "gb|gbc|dmg" },
        { "corename", "Gambatte" },
        { "manufacturer", "Nintendo" },
        { "systemname", "Game Boy/Game Boy Color" },
        { "license", "GPLv2" },
        { "permissions", "" },
        { "display_version", "v0.5.0" },
        { "need_fullpath", false },
        { "block_extract", false },
        { "supports_no_game", false }
    } },
    { "genesis_plus_gx_libretro", {
        { "display_name", "Sega MS/GG/MD/CD (Genesis Plus GX)" },
        { "authors", "Charles McDonald|Eke-Eke" },
        { "supported_extensions", "mdx|md|smd|gen|bin|cue|iso|sms|gg|sg" },
        { "corename", "Genesis Plus GX" },
        { "manufacturer", "Sega" },
        { "systemname", "Sega 8/16bit (Various)" },
        { "license", "Non-commercial" },
        { "permissions", "" },
        { "display:version", "v1.7.4" },
        { "need_fullpath", true },
        { "block_extract", false },
        { "supports_no_game", false },
        { "firmware_count", "11" },
        { "firmware0_desc", "bios_CD_E.bin (MegaCD EU BIOS)" },
        { "firmware0_path", "bios_CD_E.bin" },
        { "firmware0_opt", false },
        { "firmware1_desc", "bios_CD_U.bin (SegaCD US BIOS)" },
        { "firmware1_path", "bios_CD_U.bin" },
        { "firmware1_opt", false },
        { "firmware2_desc", "bios_CD_J.bin (MegaCD JP BIOS)" },
        { "firmware2_path", "bios_CD_J.bin" },
        { "firmware2_opt", false },
        { "firmware3_desc", "bios_E.sms (MasterSystem EU BIOS)" },
        { "firmware3_path", "bios_E.sms" },
        { "firmware3_opt", true },
        { "firmware4_desc", "bios_U.sms (MasterSystem US BIOS)" },
        { "firmware4_path", "bios_U.sms" },
        { "firmware4_opt", true },
        { "firmware5_desc", "bios_J.sms (MasterSystem JP BIOS)" },
        { "firmware5_path", "bios_J.sms" },
        { "firmware5_opt", true },
        { "firmware6", "desc" },
        { "firmware6_path", "bios.gg" },
        { "firmware6_opt", true },
        { "firmware7_desc", "sk.bin (Sonic & Knuckles (2 MiB) ROM)" },
        { "firmware7_path", "sk.bin" },
        { "firmware7_opt", true },
        { "firmware8_desc", "s2k.bin (Sonic & Knuckles UPMEM (256 KiB) ROM)" },
        { "firmware8_path", "s2k.bin" },
        { "firmware8_opt", true },
        { "firmware9_desc", "areplay.bin (Action Replay (Pro) ROM)" },
        { "firmware9_path", "areplay.bin" },
        { "firmware9_opt", true },
        { "firmware10_desc", "ggenie.bin (Game Genie ROM)" },
        { "firmware10_path", "ggenie.bin" },
        { "firmware10_opt", true },
        { "notes", "Suggested md5sums:|b4e76e416b887f4e7413ba76fa735f16 = s2k.bin" }
    } },
    { "handy_libretro", {
        { "display_name", "Lynx (Handy)" },
        { "authors", "K. Wilkins" },
        { "supported_extensions", "lnx" },
        { "corename", "Handy" },
        { "manufacturer", "Atari" },
        { "systemname", "Atari Lynx" },
        { "license", "Zlib" },
        { "permissions", "" },
        { "display_version", "0.95" },
        { "need_fullpath", true },
        { "block_extract", false },
        { "supports_no_game", false },
        { "firmware_count", "1" },
        { "firmware0_desc", "lynxboot.img (Lynx Boot Image)" },
        { "firmware0_path", "lynxboot.img" },
        { "firmware0_opt", true }
    } },
    { "hatari_libretro", {
        { "display_name", "Atari ST/STE/TT/Falcon (Hatari)" },
        { "authors", "Nicolas Pomar\u00e8de" },
        { "supported_extensions", "st|msa|zip" },
        { "corename", "Hatari" },
        { "manufacturer", "Atari" },
        { "systemname", "Atari ST/STE/TT/Falcon" },
        { "license", "GPLv2" },
        { "permissions", "" },
        { "display_version", "1.7" },
        { "need_fullpath", true },
        { "block_extract", false },
        { "supports_no_game", false },
        { "firmware_count", "1" },
        { "firmware0_desc", "tos.img (TOS image file)" },
        { "firmware0_path", "tos.img" },
        { "firmware0_opt", false }
    } },
    { "imame4all_libretro", {
        { "display_name", "Arcade (iMAME4all)" },
        { "authors", "MAMEdev" },
        { "supported_extensions", "zip|7z|chd" },
        { "corename", "iMAME4all" },
        { "manufacturer", "Various" },
        { "systemname", "Arcade (various)" },
        { "license", "GPL" },
        { "permissions", "" }
    } },
    { "mame078_libretro", {
        { "display_name", "Arcade (MAME 2003)" },
        { "authors", "MAMEdev" },
        { "supported_extensions", "zip" },
        { "corename", "MAME 2003 (0.78)" },
        { "manufacturer", "Various" },
        { "systemname", "Arcade (various)" },
        { "license", "MAME" },
        { "permissions", "" },
        { "display_version", "0.78" },
        { "need_fullpath", true },
        { "block_extract", true },
        { "supports_no_game", false }
    } },
    { "mame2010_libretro", {
        { "display_name", "Arcade (MAME 2010)" },
        { "authors", "MAMEdev" },
        { "supported_extensions", "zip|7z|chd" },
        { "corename", "MAME 2010 (0.139)" },
        { "manufacturer", "Various" },
        { "systemname", "Arcade (various)" },
        { "license", "MAME" },
        { "permissions", "" },
        { "display_version", "0.139" },
        { "need_fullpath", true },
        { "block_extract", true },
        { "supports_no_game", false }
    } },
    { "mame_libretro", {
        { "display_name", "Arcade (MAME 2014)" },
        { "authors", "MAMEdev" },
        { "supported_extensions", "zip|chd|7z" },
        { "corename", "MAME 2014 (Git)" },
        { "manufacturer", "Various" },
        { "systemname", "Arcade (various)" },
        { "license", "MAME" },
        { "permissions", "" },
        { "display_version", "Git" },
        { "need_fullpath", true },
        { "block_extract", true },
        { "supports_no_game", false },
        { "notes", "- core supports MAME save states|- core supports extracted MAME cheats|- BIOS files go into the ROM directory|- CHD files go into the ROM directory in a directory with the same name|- ARTWORK, CHEATS, SAMPLES may go into SYSTEMDIR\\mame into their own directories|- STATES, NVRAM, INPUT, SNAPS, CFG, MEMCARD, DIFF will be saved to SAVEDIR\\mame into their own directories" }
    } },
    { "mednafen_gba_libretro", {
        { "display_name", "Game Boy Advance (Mednafen GBA)" },
        { "authors", "Forgotten|VisualBoyAdvance team|Ryphecha" },
        { "supported_extensions", "gba|agb|bin" },
        { "corename", "Mednafen/Beetle GBA" },
        { "manufacturer", "Nintendo" },
        { "systemname", "Game Boy Advance" },
        { "license", "GPLv2" },
        { "permissions", "" },
        { "display_version", "v0.9.36" },
        { "need_fullpath", true },
        { "block_extract", false },
        { "supports_no_game", false },
        { "firmware_count", "1" },
        { "firmware0_desc", "gba_bios.bin (GBA BIOS)" },
        { "firmware0_path", "gba_bios.bin" },
        { "firmware0_opt", true }
    } },
    { "mednafen_lynx_libretro", {
        { "display_name", "Lynx (Mednafen Lynx)" },
        { "authors", "K. Wilkins|Ryphecha" },
        { "supported_extensions", "lnx" },
        { "corename", "Mednafen Lynx" },
        { "manufacturer", "Atari" },
        { "systemname", "Atari Lynx" },
        { "license", "Zlib|GPLv2" },
        { "permissions", "" },
        { "display_version", "v0.9.32" },
        { "need_fullpath", true },
        { "block_extract", false },
        { "supports_no_game", false },
        { "firmware_count", "1" },
        { "firmware0_desc", "lynxboot.img (Lynx Boot Image)" },
        { "firmware0_path", "lynxboot.img" },
        { "firmware0_opt", false }
    } },
    { "mednafen_ngp_libretro", {
        { "display_name", "Neo Geo Pocket/Color (Mednafen Neopop)" },
        { "authors", "neopop_uk|Ryphecha" },
        { "supported_extensions", "ngp|ngc" },
        { "corename", "Mednafen/Beetle NeoPop" },
        { "manufacturer", "SNK" },
        { "systemname", "Neo Geo Pocket (Color)" },
        { "license", "GPLv2" },
        { "permissions", "" },
        { "display_version", "v0.9.36.1" },
        { "need_fullpath", true },
        { "block_extract", false },
        { "supports_no_game", false }
    } },
    { "mednafen_pce_fast_libretro", {
        { "display_name", "PC Engine/PCE-CD (Mednafen PCE Fast)" },
        { "authors", "Ryphecha" },
        { "supported_extensions", "pce|cue|ccd" },
        { "corename", "Mednafen/Beetle PCE Fast" },
        { "manufacturer", "NEC" },
        { "systemname", "PC Engine/PCE-CD" },
        { "license", "GPLv2" },
        { "permissions", "" },
        { "display_version", "v0.9.36" },
        { "need_fullpath", true },
        { "block_extract", false },
        { "supports_no_game", false },
        { "firmware_count", "1" },
        { "firmware0_desc", "syscard3.pce (PCE-CD BIOS)" },
        { "firmware0_path", "syscard3.pce" },
        { "firmware0_opt", false }
    } },
    { "mednafen_pcfx_libretro", {
        { "display_name", "PC-FX (Mednafen PC-FX)" },
        { "authors", "Ryphecha" },
        { "supported_extensions", "cue|ccd|toc" },
        { "corename", "Mednafen/Beetle PC-FX" },
        { "manufacturer", "NEC" },
        { "systemname", "PC-FX" },
        { "license", "GPLv2" },
        { "permissions", "" },
        { "display_version", "v0.9.33.3" },
        { "need_fullpath", true },
        { "block_extract", false },
        { "supports_no_game", false },
        { "firmware_count", "1" },
        { "firmware0_desc", "pcfx.bios (PC-FX BIOS)" },
        { "firmware0_path", "pcfx.bios" },
        { "firmware0_opt", false }
    } },
    { "mednafen_psx_libretro", {
        { "display_name", "PlayStation1 (Mednafen PSX)" },
        { "authors", "Ryphecha" },
        { "supported_extensions", "cue|toc|m3u|ccd|exe" },
        { "corename", "Mednafen/Beetle PSX" },
        { "manufacturer", "Sony" },
        { "systemname", "PlayStation" },
        { "license", "GPLv2" },
        { "permissions", "" },
        { "display_version", "v0.9.36" },
        { "need_fullpath", true },
        { "block_extract", false },
        { "supports_no_game", false },
        { "firmware_count", "3" },
        { "firmware0_desc", "scph5500.bin (PS1 JP BIOS)" },
        { "firmware0_path", "scph5500.bin" },
        { "firmware0_opt", false },
        { "firmware1_desc", "scph5501.bin (PS1 US BIOS)" },
        { "firmware1_path", "scph5501.bin" },
        { "firmware1_opt", false },
        { "firmware2_desc", "scph5502.bin (PS1 EU BIOS)" },
        { "firmware2_path", "scph5502.bin" },
        { "firmware2_opt", false },
        { "notes", "Suggested md5sums:|8dd7d5296a650fac7319bce665a6a53c = scph5500.bin|490f666e1afb15b7362b406ed1cea246 = scph5501.bin|32736f17079d0b2b7024407c39bd3050 = scph5502.bin" }
    } },
    { "mednafen_snes_libretro", {
        { "display_name", "SNES / Super Famicom (Mednafen SNES)" },
        { "supported_extensions", "smc|fig|bs|st|sfc" },
        { "corename", "Mednafen/Beetle bSNES" },
        { "manufacturer", "Nintendo" },
        { "systemname", "Super Nintendo Entertainment System" },
        { "license", "GPLv2" },
        { "permissions", "" },
        { "display_version", "v0.9.26" },
        { "need_fullpath", true },
        { "block_extract", false },
        { "supports_no_game", false }
    } },
    { "mednafen_supergrafx_libretro", {
        { "display_name", "PC Engine SuperGrafx (Mednafen PCE Fast)" },
        { "authors", "Ryphecha" },
        { "supported_extensions", "pce|sgx" },
        { "corename", "Mednafen/Beetle SuperGrafx" },
        { "manufacturer", "NEC" },
        { "systemname", "PC Engine SuperGrafx" },
        { "license", "GPLv2" },
        { "permissions", "" },
        { "display_version", "v0.9.36" },
        { "need_fullpath", true },
        { "block_extract", false },
        { "supports_no_game", false }
    } },
    { "mednafen_vb_libretro", {
        { "display_name", "Virtual Boy (Mednafen VB)" },
        { "authors", "Ryphecha" },
        { "supported_extensions", "vb|vboy|bin" },
        { "corename", "Mednafen/Beetle VB" },
        { "manufacturer", "Nintendo" },
        { "systemname", "Virtual Boy" },
        { "license", "GPLv2" },
        { "permissions", "" },
        { "display_version", "v0.9.33.3" },
        { "need_fullpath", true },
        { "block_extract", false },
        { "supports_no_game", false }
    } },
    { "mednafen_wswan_libretro", {
        { "display_name", "WonderSwan/Color (Mednafen Cygne)" },
        { "authors", "Dox|Ryphecha" },
        { "supported_extensions", "ws|wsc" },
        { "corename", "Mednafen/Beetle WonderSwan" },
        { "manufacturer", "Bandai" },
        { "systemname", "WonderSwan/Color" },
        { "license", "GPLv2" },
        { "permissions", "" },
        { "display_version", "v0.9.35.1" },
        { "need_fullpath", true },
        { "block_extract", false },
        { "supports_no_game", false }
    } },
    { "mess_libretro", {
        { "display_name", "Computers, video game consoles and calculators (MESS 2014)" },
        { "authors", "MAMEdev" },
        { "supported_extensions", "zip|chd|7z" },
        { "corename", "MESS 2014 (Git)" },
        { "manufacturer", "Various" },
        { "systemname", "Computers, video game consoles and calculators (various)" },
        { "license", "MAME" },
        { "permissions", "" },
        { "display_version", "Git" },
        { "need_fullpath", true },
        { "block_extract", true },
        { "supports_no_game", false },
        { "notes", "- To load roms, you need the hashes in SYSTEMDIR\\mess\\hash and softlist romset|- You can get the hashes from the mame/mess source code|- core supports MESS save states|- core supports extracted MESS cheats|- BIOS files go into the ROM directory|- CHD files go into the ROM directory in a directory with the same name|- ARTWORK, CHEATS, SAMPLES may go into SYSTEMDIR\\mess into their own directories|- STATES, NVRAM, INPUT, SNAPS, CFG, MEMCARD, DIFF will be saved to SAVEDIR\\mess into their own directories" }
    } },
    { "meteor_libretro", {
        { "display_name", "Game Boy Advance (Meteor)" },
        { "supported_extensions", "gba" },
        { "authors", "Philippe Daouadi" },
        { "corename", "Meteor" },
        { "manufacturer", "Nintendo" },
        { "systemname", "Game Boy Advance" },
        { "license", "GPLv3" },
        { "permissions", "" },
        { "display_version", "v1.4" },
        { "need_fullpath", false },
        { "block_extract", false },
        { "supports_no_game", false }
    } },
    { "mupen64plus_libretro", {
        { "display_name", "Nintendo 64 (Mupen64plus)" },
        { "supported_extensions", "n64|v64|z64" },
        { "corename", "Mupen64Plus" },
        { "manufacturer", "Nintendo" },
        { "systemname", "Nintendo 64" },
        { "license", "GPLv2" },
        { "permissions", "dynarec_optional" },
        { "display_version", "2.0-rc2" },
        { "need_fullpath", false },
        { "block_extract", false },
        { "supports_no_game", false }
    } },
    { "nestopia_libretro", {
        { "display_name", "NES / Famicom (NEStopia)" },
        { "supported_extensions", "nes|fds" },
        { "authors", "Martin Freij" },
        { "corename", "Nestopia" },
        { "manufacturer", "Nintendo" },
        { "systemname", "Nintendo Entertainment System" },
        { "license", "GPLv2" },
        { "permissions", "" },
        { "display_version", "v1.46-WIP" },
        { "need_fullpath", false },
        { "block_extract", false },
        { "supports_no_game", false },
        { "firmware_count", "1" },
        { "firmware0_desc", "disksys.rom (Famicom Disk System BIOS)" },
        { "firmware0_path", "disksys.rom" },
        { "firmware0_opt", false }
    } },
    { "nxengine_libretro", {
        { "display_name", "Cave Story (NXEngine)" },
        { "authors", "Caitlin Shaw" },
        { "supported_extensions", "exe" },
        { "corename", "NXEngine" },
        { "systemname", "Cave Story game engine" },
        { "license", "GPLv3" },
        { "permissions", "" },
        { "display_version", "1.0.0.4" },
        { "need_fullpath", true },
        { "block_extract", false },
        { "supports_no_game", false }
    } },
    { "o2em_libretro", {
        { "display_name", "Odyssey 2/VideoPac (O2EM)" },
        { "authors", "Daniel Boris|Andre de la Rocha|Arlindo M. de Oliveira" },
        { "supported_extensions", "bin" },
        { "corename", "Odyssey 2/VideoPac" },
        { "manufacturer", "Magnavox|Philips" },
        { "systemname", "Magnavox Odyssey 2/VideoPac" },
        { "license", "Artistic License" },
        { "permissions", "" },
        { "display_version", "1.18" },
        { "need_fullpath", false },
        { "block_extract", false },
        { "supports_no_game", false },
        { "firmware_count", "1" },
        { "firmware0_desc", "o2rom.bin (Odyssey 2 BIOS)" },
        { "firmware0_path", "o2rom.bin" },
        { "firmware0_opt", false }
    } },
    { "pcsx_rearmed_libretro", {
        { "display_name", "PlayStation1 (PCSX ReARMed)" },
        { "authors", "PCSX Team|notaz|Exophase" },
        { "supported_extensions", "bin|cue|img|mdf|pbp|toc|cbn|m3u" },
        { "corename", "PCSX ReARMed" },
        { "manufacturer", "Sony" },
        { "systemname", "PlayStation" },
        { "license", "GPLv2" },
        { "permissions", "dynarec" },
        { "display_version", "r19" },
        { "need_fullpath", true },
        { "block_extract", false },
        { "supports_no_game", false },
        { "firmware_count", "3" },
        { "firmware0_desc", "scph5500.bin (PS1 JP BIOS)" },
        { "firmware0_path", "scph5500.bin" },
        { "firmware0_opt", true },
        { "firmware1_desc", "scph5501.bin (PS1 US BIOS)" },
        { "firmware1_path", "scph5501.bin" },
        { "firmware1_opt", true },
        { "firmware2_desc", "scph5502.bin (PS1 EU BIOS)" },
        { "firmware2_path", "scph5502.bin" },
        { "firmware2_opt", true }
    } },
    { "pcsx_rearmed_libretro_neon", {
        { "display_name", "PlayStation1 (PCSX ReARMed) [NEON]" },
        { "authors", "PCSX Team|notaz|Exophase" },
        { "supported_extensions", "bin|cue|img|mdf|pbp|toc|cbn|m3u" },
        { "corename", "PCSX ReARMed [NEON]" },
        { "manufacturer", "Sony" },
        { "systemname", "PlayStation" },
        { "license", "GPLv2" },
        { "permissions", "dynarec" },
        { "display_version", "r19" },
        { "need_fullpath", true },
        { "block_extract", false },
        { "supports_no_game", false },
        { "firmware_count", "3" },
        { "firmware0_desc", "scph5500.bin (PS1 JP BIOS)" },
        { "firmware0_path", "scph5500.bin" },
        { "firmware0_opt", true },
        { "firmware1_desc", "scph5501.bin (PS1 US BIOS)" },
        { "firmware1_path", "scph5501.bin" },
        { "firmware1_opt", true },
        { "firmware2_desc", "scph5502.bin (PS1 EU BIOS)" },
        { "firmware2_path", "scph5502.bin" },
        { "firmware2_opt", true }
    } },
    { "picodrive_libretro", {
        { "display_name", "Sega MS/GG/MD/CD/32X (Picodrive)" },
        { "authors", "notaz|fdave" },
        { "supported_extensions", "bin|gen|smd|md|32x|cue|iso|sms" },
        { "corename", "Picodrive" },
        { "manufacturer", "Sega" },
        { "systemname", "Sega 16bit + 32X (Various)" },
        { "license", "MAME" },
        { "permissions", "dynarec_optional" },
        { "display_version", "1.91" },
        { "need_fullpath", true },
        { "block_extract", false },
        { "supports_no_game", false },
        { "firmware_count", "3" },
        { "firmware0_desc", "bios_CD_E.bin (MegaCD EU BIOS)" },
        { "firmware0_path", "bios_CD_E.bin" },
        { "firmware0_opt", false },
        { "firmware1_desc", "bios_CD_U.bin (SegaCD US BIOS)" },
        { "firmware1_path", "bios_CD_U.bin" },
        { "firmware1_opt", false },
        { "firmware2_desc", "bios_CD_J.bin (MegaCD JP BIOS)" },
        { "firmware2_path", "bios_CD_J.bin" },
        { "firmware2_opt", false }
    } },
    { "pocketsnes_libretro", {
        { "display_name", "SNES / Super Famicom (PocketSNES)" },
        { "authors", "SNES9x Team|PocketSNES Team|Toadking" },
        { "supported_extensions", "smc|fig|sfc|gd3|gd7|dx2|bsx|swc" },
        { "corename", "PocketSNES" },
        { "manufacturer", "Nintendo" },
        { "systemname", "Super Nintendo Entertainment System" },
        { "license", "Non-commercial" },
        { "permissions", "" }
    } },
    { "ppsspp_libretro", {
        { "display_name", "PSP (PlayStation Portable)" },
        { "authors", "Henrik Hrydgard" },
        { "supported_extensions", "elf|iso|cso|prx|pbp" },
        { "corename", "PPSSPP" },
        { "manufacturer", "Sony" },
        { "systemname", "PSP" },
        { "license", "GPLv2" },
        { "permissions", "" },
        { "display_version", "v0.9.9.1" },
        { "need_fullpath", true },
        { "block_extract", false },
        { "supports_no_game", false }
    } },
    { "prboom_libretro", {
        { "display_name", "Doom (PrBoom)" },
        { "supported_extensions", "wad|iwad" },
        { "corename", "PrBoom" },
        { "systemname", "DOOM game engine" },
        { "license", "GPLv2" },
        { "permissions", "" },
        { "display_version", "v2.5.0" },
        { "need_fullpath", false },
        { "block_extract", false },
        { "supports_no_game", false },
        { "notes", "- prboom.wad needs to be in the ROM directory|" }
    } },
    { "prosystem_libretro", {
        { "display_name", "Atari 7800 (ProSystem)" },
        { "authors", "Greg Stanton|Brian Berlin|Leonis|Greg DeMent" },
        { "supported_extensions", "a78|bin" },
        { "corename", "ProSystem" },
        { "manufacturer", "Atari" },
        { "systemname", "Atari 7800" },
        { "license", "GPLv2" },
        { "permissions", "" },
        { "display_version", "1.3e" },
        { "need_fullpath", false },
        { "block_extract", false },
        { "supports_no_game", false },
        { "firmware_count", "2" },
        { "firmware0_desc", "ProSystem.dat (Atari 7800 Database)" },
        { "firmware0_path", "ProSystem.dat" },
        { "firmware0_opt", true },
        { "firmware1_desc", "7800 BIOS (U).rom (Atari 7800 BIOS)" },
        { "firmware1_path", "7800 BIOS (U).rom" },
        { "firmware1_opt", true }
    } },
    { "puae_libretro", {
        { "display_name", "Amiga (P-UAE)" },
        { "authors", "GnoStiC" },
        { "supported_extensions", "adf|dms|fdi|ipf|zip" },
        { "corename", "PUAE" },
        { "manufacturer", "Commodore" },
        { "systemname", "Commodore Amiga" },
        { "license", "GPLv2" },
        { "permissions", "" },
        { "display_version", "v2.6.1" },
        { "need_fullpath", true },
        { "block_extract", false },
        { "supports_no_game", false }
    } },
    { "quicknes_libretro", {
        { "display_name", "NES / Famicom (QuickNES)" },
        { "authors", "blargg|kode54" },
        { "supported_extensions", "nes" },
        { "corename", "QuickNES" },
        { "manufacturer", "Nintendo" },
        { "systemname", "Nintendo Entertainment System" },
        { "license", "GPLv2" },
        { "permissions", "" },
        { "display_version", "v1" },
        { "need_fullpath", false },
        { "block_extract", false },
        { "supports_no_game", false }
    } },
    { "remotejoy_libretro", {
        { "display_name", "PSP RemotePlay (RemoteJoy)" },
        { "authors", "" },
        { "supported_extensions", "" },
        { "corename", "RemoteJoy" },
        { "systemname", "PSP RemotePlay" },
        { "license", "GPLv2" },
        { "permissions", "" },
        { "display_version", "v1" },
        { "need_fullpath", false },
        { "block_extract", false },
        { "supports_no_game", true }
    } },
    { "scummvm_libretro", {
        { "display_name", "ScummVM" },
        { "authors", "SCUMMVMdev" },
        { "supported_extensions", "exe" },
        { "corename", "ScummVM" },
        { "systemname", "ScummVM" },
        { "license", "GPLv2" },
        { "permissions", "" },
        { "display_version", "git" },
        { "need_fullpath", true },
        { "block_extract", false },
        { "supports_no_game", true }
    } },
    { "snes9x_libretro", {
        { "display_name", "SNES / Super Famicom (SNES9x)" },
        { "authors", "SNES9x Team" },
        { "supported_extensions", "smc|sfc|swc|fig" },
        { "corename", "SNES9x" },
        { "manufacturer", "Nintendo" },
        { "systemname", "Super Nintendo Entertainment System" },
        { "license", "Non-commercial" },
        { "permissions", "" },
        { "display_version", "1.53" },
        { "need_fullpath", false },
        { "block_extract", false },
        { "supports_no_game", false }
    } },
    { "snes9x_next_libretro", {
        { "display_name", "SNES / Super Famicom (SNES9x Next)" },
        { "authors", "SNES9x Team|Squarepusher" },
        { "supported_extensions", "smc|fig|sfc|gd3|gd7|dx2|bsx|swc" },
        { "corename", "SNES9x Next" },
        { "manufacturer", "Nintendo" },
        { "systemname", "Super Nintendo Entertainment System" },
        { "license", "Non-commercial" },
        { "permissions", "" },
        { "display_version", "v1.52.4" },
        { "need_fullpath", false },
        { "block_extract", false },
        { "supports_no_game", false }
    } },
    { "stella_libretro", {
        { "display_name", "Atari 2600 (Stella)" },
        { "authors", "Stephen Anthony|Bradford Mott|Eckhard Stolberg|Brian Watson" },
        { "supported_extensions", "a26|bin" },
        { "corename", "Stella" },
        { "manufacturer", "Atari" },
        { "systemname", "Atari 2600" },
        { "license", "GPLv2" },
        { "permissions", "" },
        { "display_version", "3.9.3" },
        { "need_fullpath", false },
        { "block_extract", false },
        { "supports_no_game", false }
    } },
    { "tgbdual_libretro", {
        { "display_name", "Game Boy / Game Boy Color (TGB Dual)" },
        { "authors", "GIGO|Hii" },
        { "supported_extensions", "gb|gbc|sgb" },
        { "corename", "TGB Dual" },
        { "manufacturer", "Nintendo" },
        { "systemname", "Game Boy/Game Boy Color" },
        { "license", "GPLv2" },
        { "permissions", "" },
        { "display_version", "" },
        { "need_fullpath", false },
        { "block_extract", false },
        { "supports_no_game", false }
    } },
    { "tyrquake_libretro", {
        { "display_name", "Quake 1 (TyrQuake)" },
        { "supported_extensions", "pak" },
        { "corename", "TyrQuake" },
        { "systemname", "Quake 1 game engine" },
        { "license", "GPLv2" },
        { "permissions", "" },
        { "display_version", "v0.62" },
        { "need_fullpath", false },
        { "block_extract", false },
        { "supports_no_game", false }
    } },
    { "vba_next_libretro", {
        { "display_name", "Game Boy Advance (VBA Next)" },
        { "authors", "Forgotten|VBA-M Team|Squarepusher" },
        { "supported_extensions", "gba" },
        { "corename", "VBA Next" },
        { "manufacturer", "Nintendo" },
        { "systemname", "Game Boy Advance" },
        { "license", "GPLv2" },
        { "permissions", "" },
        { "display_version", "svn" },
        { "need_fullpath", true },
        { "block_extract", false },
        { "supports_no_game", false }
    } },
    { "vbam_libretro", {
        { "display_name", "Game Boy Advance (VBA-M)" },
        { "authors", "Forgotten|VBA-M Team" },
        { "supported_extensions", "gba" },
        { "corename", "VBA-M" },
        { "manufacturer", "Nintendo" },
        { "systemname", "Game Boy Advance" },
        { "license", "GPLv2" },
        { "permissions", "" },
        { "display_version", "svn" },
        { "need_fullpath", false },
        { "block_extract", false },
        { "supports_no_game", false }
    } },
    { "vecx_libretro", {
        { "display_name", "Vectrex (vecx)" },
        { "authors", "Valavan Manohararajah|John Hawthorn|Nikita Zimin|Demeth" },
        { "supported_extensions", "bin|vec" },
        { "corename", "vecx" },
        { "manufacturer", "Smith Engineering|General Consumer Electronics" },
        { "systemname", "Vectrex" },
        { "license", "GPLv2" },
        { "permissions", "" },
        { "display_version", "svn" },
        { "need_fullpath", true },
        { "block_extract", false },
        { "supports_no_game", false }
    } },
    { "virtualjaguar_libretro", {
        { "display_name", "Atari Jaguar (Virtual Jaguar)" },
        { "authors", "David Raingeard|Shamus" },
        { "supported_extensions", "j64|jag" },
        { "corename", "Virtual Jaguar" },
        { "manufacturer", "Atari" },
        { "systemname", "Jaguar" },
        { "license", "GPLv3" },
        { "permissions", "" },
        { "display_version", "v2.1.0" },
        { "need_fullpath", false },
        { "block_extract", false },
        { "supports_no_game", false }
    } },
    { "yabause_libretro", {
        { "display_name", "Sega Saturn (Yabause)" },
        { "authors", "Guillaume Duhammel|Theo Berkau|Anders Montonen" },
        { "supported_extensions", "bin|cue|iso" },
        { "corename", "Yabause" },
        { "manufacturer", "Sega" },
        { "systemname", "Saturn" },
        { "license", "GPLv2" },
        { "display_version", "v0.9.13" },
        { "need_fullpath", true },
        { "block_extract", false },
        { "supports_no_game", false },
        { "firmware_count", "1" },
        { "firmware0_desc", "saturn_bios.bin (Saturn BIOS)" },
        { "firmware0_path", "saturn_bios.bin" },
        { "firmware0_opt", true }
    } }
};
