
#ifndef LOGGING_H
#define LOGGING_H

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(phxCore)
Q_DECLARE_LOGGING_CATEGORY(phxVideo)
Q_DECLARE_LOGGING_CATEGORY(phxAudio)
Q_DECLARE_LOGGING_CATEGORY(phxInput)
Q_DECLARE_LOGGING_CATEGORY(phxLibrary)

#endif
